CREATE TABLE task (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deadline DATE,
    name VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    task_status VARCHAR(255) NOT NULL,

    CONSTRAINT task_status_check
                  CHECK ( task_status IN ('PENDING', 'COMPLETED'))
);